module.exports = {
  docs: [
    'index',
    'why-git-dedup',
    { type: 'category', label: 'CLI reference', items: [{ type: 'autogenerated', dirName: 'cli' }] },
    'agents',
    'editors',
    'how-it-works',
    'safety',
  ],
};
